CREATE TABLE if not exists `Users` (
`id` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
`username` varchar(255) NOT NULL, 
`password` varchar(255) NOT NULL, 
 `pos1B` int(11),
 `pos2B` int(11),
 `pos3B` int(11),
 `posLF` int(11),
 `posCF` int(11),
 `posRF` int(11),
 `posSS` int(11),
 `posC` int(11),
 `posP` int(11),
 FOREIGN KEY (pos1B) REFERENCES Player(id),
 FOREIGN KEY (pos2B) REFERENCES Player(id),
 FOREIGN KEY (pos3B) REFERENCES Player(id),
 FOREIGN KEY (posSS) REFERENCES Player(id),
 FOREIGN KEY (posC) REFERENCES Player(id),
 FOREIGN KEY (posP) REFERENCES Player(id),
 FOREIGN KEY (posLF) REFERENCES Player(id),
 FOREIGN KEY (posRF) REFERENCES Player(id),
 FOREIGN KEY (posCF) REFERENCES Player(id));